version: '3'

services:
  bot-security-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=
      - POSTGRESQL_PASSWORD=
      - POSTGRESQL_DATABASE=